version: "3.8"

services:
  # CMS (Statamic)
  statamic:
    build: ./cms-statamic
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - statamic-content:/var/www/html/content
      - ./cms-statamic/volum:/var/salut
    networks:
      - app-network
    command: >
      bash -c "sleep 10 &&
              php artisan cache:clear &&
              php artisan statamic:stache:clear &&
              chown -R www-data:www-data /var/www/html/content &&
              chmod -R 775 /var/www/html/content &&
              chown -R www-data:www-data /var/www/html/storage &&
              chmod -R 775 /var/www/html/storage &&
              apache2-foreground"

  # MySQL pentru Statamic
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: statamic_db
      MYSQL_USER: statamic_user
      MYSQL_PASSWORD: statamic_pass
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # Chat Backend (Node.js + WebSocket)
  chat-backend:
    build: ./chat-app/chat-backend
    depends_on:
      - mongodb
    networks:
      - app-network

  # Chat Frontend (Vue.js)
  chat-frontend:
    build: ./chat-app/chat-frontend
    ports:
      - "90:80"
    depends_on:
      - chat-nginx
    networks:
      - app-network

  # Chat Nginx
  chat-nginx:
    build: ./chat-app/chat-nginx
    ports:
      - "88:88"
    depends_on:
      - chat-backend
    networks:
      - app-network

  # MongoDB pentru Chat
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # IA Backend
  ai-backend:
    build: ./IA-app/ai-backend
    volumes:
      - ./IA-app/ai-backend/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000
    expose:
      - "3000"
    networks:
      - app-network

  ai-frontend:
    build: ./IA-app/ai-frontend
    ports:
      - "8080:80"
    depends_on:
      - ai-backend
    networks:
      - app-network

  # IA Apache (include frontend-ul Vue.js)
  ai-apache:
    build: ./IA-app/ai-apache
    ports:
      - "8081:80"
    depends_on:
      - ai-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  mongo-data:
  statamic-content:
