apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\alexm\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ai-apache
  name: ai-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ai-apache
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\alexm\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --out k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: ai-apache
    spec:
      containers:
        - image: localhost:30500/ai-apache:latest
          name: ai-apache
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
