apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ai-backend
  template:
    metadata:
      labels:
        io.kompose.service: ai-backend  # Adăugat pentru a se potrivi cu selector
    spec:
      containers:
      - name: ai-backend
        image: aless2303/ai-backend:latest
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3000"
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: AZURE_STORAGE_CONNECTION_STRING
        - name: AZURE_SQL_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: AZURE_SQL_CONNECTION_STRING
        - name: AZURE_VISION_KEY
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: AZURE_VISION_KEY
        - name: AZURE_VISION_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: AZURE_VISION_ENDPOINT