apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\alexm\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ai-frontend
  name: ai-frontend
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
      nodePort: 30081
  selector:
    io.kompose.service: ai-frontend
  type: NodePort
