apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\alexm\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ai-frontend
  name: ai-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ai-frontend
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\alexm\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --out k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: ai-frontend
    spec:
      containers:
        - image: aless2303/ai-frontend:latest
          name: ai-frontend
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
