apiVersion: v1
kind: Service
metadata:
  name: chat-backend
  labels:
    io.kompose.service: chat-backend
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: chat-backend