apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-nginx-config
data:
  nginx.conf: |
    server {
        listen 88;
        server_name localhost;

        location / {
            proxy_pass http://chat-backend:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }