apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\alexm\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: chat-backend
  name: chat-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chat-backend
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\alexm\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --out k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: chat-backend
    spec:
      containers:
        - image: chat-backend
          name: chat-backend
      restartPolicy: Always
