apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\alexm\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: chat-backend
  name: chat-backend
spec:
  replicas: 2  
  selector:
    matchLabels:
      io.kompose.service: chat-backend
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\alexm\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --out k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: chat-backend
    spec:
      containers:
        - name: chat-backend
          image: localhost:30500/ai-frontend:latest
          env:
            - name: NODE_ENV
              value: production
            - name: MONGO_URI
              value: mongodb://mongodb:27017/chatdb
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always