apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\alexm\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: chat-nginx
  name: chat-nginx
spec:
  replicas: 2  # Modificat conform cerințelor
  selector:
    matchLabels:
      io.kompose.service: chat-nginx
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\alexm\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --out k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: chat-nginx
    spec:
      containers:
        - name: chat-nginx
          image: localhost:30500/chat-nginx:latest
          ports:
            - containerPort: 88
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: chat-nginx-config
      restartPolicy: Always