apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\alexm\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: chat-nginx
  name: chat-nginx
spec:
  ports:
    - name: "88"
      port: 88
      targetPort: 88
  selector:
    io.kompose.service: chat-nginx
