apiVersion: apps/v1
kind: Deployment
metadata:
  name: statamic
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: statamic
  template:
    metadata:
      labels:
        io.kompose.service: statamic
    spec:
      initContainers:
        - name: copy-content
          image: localhost:32000/statamic
          command: ["sh", "-c", "cp -r /var/www/html/content/* /mnt/content/ || true"]
          volumeMounts:
            - name: statamic-content
              mountPath: /mnt/content
      containers:
        - name: statamic
          image: localhost:32000/statamic
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html/content
              name: statamic-content
          command:
            - bash
            - -c
            - |
              php artisan cache:clear &&
              php artisan statamic:stache:clear &&
              chown -R www-data:www-data /var/www/html/content &&
              chmod -R 775 /var/www/html/content &&
              chown -R www-data:www-data /var/www/html/storage &&
              chmod -R 775 /var/www/html/storage &&
              apache2-foreground
      volumes:
        - name: statamic-content
          persistentVolumeClaim:
            claimName: statamic-content