apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: statamic-content
  name: statamic-content
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi