apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\alexm\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: statamic
  name: statamic
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: statamic
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\alexm\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --out k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: statamic
    spec:
      containers:
        - args:
            - bash
            - -c
            - |-
              php artisan cache:clear &&
                       php artisan statamic:stache:clear &&
                       chown -R www-data:www-data /var/www/html/content &&
                       chmod -R 775 /var/www/html/content &&
                       chown -R www-data:www-data /var/www/html/storage &&
                       chmod -R 775 /var/www/html/storage &&
                       apache2-foreground
          image: statamic
          name: statamic
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html/content
              name: statamic-content
      restartPolicy: Always
      volumes:
        - name: statamic-content
          persistentVolumeClaim:
            claimName: statamic-content
