apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
  namespace: mta-project
spec:
  replicas: 2  # 2 replici conform cerinței
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
      - name: chat-backend
        image: localhost:5000/chat-backend:latest
        env:
        - name: MONGO_URI
          value: mongodb://mongodb:27017/chat
        - name: NODE_ENV
          value: production
        ports:
        - containerPort: 3000